### ISSUE TITLE
`module+` errors when used at phase 2

### ISSUE THREAD

**Issue by florence** [racket/racket#1312]
```racket
#lang racket/base
(require (for-syntax racket/base))
(begin-for-syntax
  (require (for-syntax racket/base))
  (module+ test 1)
  (begin-for-syntax
    (module+ test1 1)))
```

Produces the error:

```
begin-for-syntax: unbound identifier in the transformer environment;
 also, no #%app syntax transformer is bound
  context...:
   #(2 module) #(499 module begin-mod 1) #(655 module #%kernel 1)
  other binding...:
   #<module-path-index:(racket/base)>
   #(497 module) #(499 module begin-mod 1)
  at: begin-for-syntax
  in: (begin-for-syntax (define-module test1))
  context...:
   standard-module-name-resolver
```
