### ISSUE TITLE
Using keyword arguments inside of a case-> contract produces an internal error

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1369]
I have, at times, written a function that I might want to accept a by-position argument *or* a keyword argument, but not both. Here’s a contrived example that implements such a function:

```racket
(define (foo [a #f] #:b [b #f])
  (if a (* a 2) (* b 2)))
```

I would like to assign that function the following contract:

```racket
(case-> (number? . -> . number?)
        (#:b number? . -> . number?))
```

However, running the above expression produces an error from inside `racket/contract`:

```
application: procedure does not accept keyword arguments
  procedure: list
  arguments...:
   #:b #<procedure:number?>
```

Ideally, I would really like to be able to write the above contract, but if that’s too much work, it would be nice for it to be a syntax error. At the very least it should be a more useful runtime error, but I think generally it would be nicer if this were a compile-time error, since the `->` contract combinators seem to mostly catch this sort of thing statically.
