### ISSUE TITLE
->i fails with internal error message

### ISSUE THREAD

**Issue by endobson** [racket/racket#1845]
Program:
```
#lang racket/base
(require racket/contract)

(->i ([arg1 any/c] [_ (arg1) any/c]) [_ (arg1) any/c])
```
Output:
```
_-dom-blame: unbound identifier in module
  context...:
   #(516 module) #(517 module test 0) #(1512 local) #(1513 intdef) #(1514 local)
   #(1530 intdef) #(1607 local) #(1608 intdef) #(1611 local) #(1612 intdef)
   #(1621 local) #(1622 intdef) #(1624 local) #(1625 intdef) #(1627 local)
   #(1630 intdef) #(1632 local) #(1634 intdef)
  other binding...:
   local _-dom-blame41
   #(-166334783135379187 module) #(-166334783135379184 module arr-i-parse -1)
   #(517 module test 0) #(1451 macro) #(1512 local) #(1513 intdef) #(1514 local)
   #(1530 intdef) #(1607 local)
  in: _-dom-blame
```

Racket version: ed5911e5316fa457c4805774756a060ba4ef4b5c
