### ISSUE TITLE
nonrecoverable invalid memory reference from recent racketcs

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#3397]
This problem is identified in https://github.com/racket/typed-racket/pull/968 , but I create the issue here and leave that PR for its original purpose since this is probably relevant to recent changes in racketcs.

The minimal config I found to reproduce the problem is
```
on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current"]
        racket-variant: ["CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.10
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: |
             sudo raco pkg install --auto -i --no-setup --skip-installed typed-racket-test
      - run: xvfb-run racket -l typed-racket-test -- --just `racket -e '(displayln (collection-file-path "succeed/gui-lang.rkt" "typed-racket-test"))'`
```
An sampled run is here : https://github.com/yjqww6/ci-test/runs/1099988427
