### ISSUE TITLE
A better error for non-interactive raco pkg install

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3523]
**What version of Racket are you using?**
7.9 [cs]

**What program did you run?**

Run `raco pkg install` on any package with a dependency in a non-interactive environment (e.g., CI). 

For example:

```
raco pkg install rosette
```

**What should have happened?**

It makes sense that there is an error (see below) because the prompt "Would you like to install these dependencies? [Y/n/a/c/?] " can't be answered. However, it is pretty cryptic. It would be nice if the error is improved. Suggesting users to provide `--auto` would even be better.

**If you got an error message, please include it here.**

```
string-trim: contract violation
  expected: string?
  given: #<eof>
  context...:
```

**Please include any other relevant details**
N/A
