### ISSUE TITLE
`impersonate-box` can't work for `impersonate-box`.

### ISSUE THREAD

**Issue by NoahStoryM** [racket/racket#4111]
**What version of Racket are you using?**
`v8.3.0.10 [cs]`

**What program did you run?**
```
#lang racket

(define b1
  (impersonate-box (box 'hi)
                   (λ (b o) o)
                   (λ (b i) i)))

(displayln ((and/c box? (not/c immutable?)) b1))

(define b2
  (impersonate-box b1
                   (λ (b o) o)
                   (λ (b i) i)))
```

**What should have happened?**
no error

**If you got an error message, please include it here.**
```
impersonate-box: contract violation
  expected: (and/c box? (not/c immutable?))
  given: '#&hi
  context...:
   body of "/home/noah/Desktop/Codes/Racket/draft.rkt"
```

**Please include any other relevant details**
It's ok for `chaperone-box`:
```
#lang racket

(define b1
  (impersonate-box (box 'hi)
                   (λ (b o) o)
                   (λ (b i) i)))

(displayln ((and/c box? (not/c immutable?)) b1))

(define b2
  (chaperone-box b1
                 (λ (b o) o)
                 (λ (b i) i)))

```

And I'm not sure if other impersonate operators have the same problem.
